#define TRAINER_NONE 0

// Route 6
#define TRAINER_ROUTE6_BUGCATCHER_HORACE         2
#define TRAINER_ROUTE6_YOUNGSTER_MARUYAMA        3
#define TRAINER_ROUTE6_SUPERNERD_DIETER_1        4
#define TRAINER_ROUTE6_YOUNGSTER_MARUYAMA_2      11

// Iced Path
#define TRAINER_ICEDPATH_SWIMMER_FRANCINE        5
#define TRAINER_ICEDPATH_CAMPER_TROY		     6
#define TRAINER_ICEDPATH_CAMPER_ROSS		     7

// Route 7
#define TRAINER_ROUTE7_INFIELDER_DELBERT		 12

// Celadon City
#define TRAINER_CELADON_ROCKETGRUNT_LEFT 9
#define TRAINER_CELADON_ROCKETGRUNT_RIGHT 10

// Celadon Dept Store - Rocket Event
#define TRAINER_DEPTSTORE_ROCKETGRUNT_1F 22
#define TRAINER_DEPTSTORE_ROCKETGRUNT_2F_1 23
#define TRAINER_DEPTSTORE_ROCKETGRUNT_2F_2 24
#define TRAINER_DEPTSTORE_ROCKETGRUNT_4F_1 25
#define TRAINER_DEPTSTORE_ROCKETGRUNT_4F_2 26
#define TRAINER_DEPTSTORE_ROCKETGRUNT_5F_1 27
#define TRAINER_DEPTSTORE_ROCKETGRUNT_5F_2 28

// Rival Battle 1
#define TRAINER_RIVALBATTLE1_PLAYER_CHOSE_RELICANTH 13
#define TRAINER_RIVALBATTLE1_PLAYER_CHOSE_SIGILYPH 14
#define TRAINER_RIVALBATTLE1_PLAYER_CHOSE_PASSIMIAN 15

// Sibling Battle 1
#define TRAINER_BRANDYBATTLE1_PLAYER_CHOSE_RELICANTH 16
#define TRAINER_BRANDYBATTLE1_PLAYER_CHOSE_SIGILYPH 17
#define TRAINER_BRANDYBATTLE1_PLAYER_CHOSE_PASSIMIAN 18
#define TRAINER_SHERRYBATTLE1_PLAYER_CHOSE_RELICANTH 19
#define TRAINER_SHERRYBATTLE1_PLAYER_CHOSE_SIGILYPH 20
#define TRAINER_SHERRYBATTLE1_PLAYER_CHOSE_PASSIMIAN 21

// Garchomp Gavin
#define TRAINER_CELADON_GARCHOMPGAVIN1 8

// Jessie & James
#define TRAINER_CELADON_JESSIEJAMES1 29
#define TRAINER_DEPTSTORE_SHERRYPARTNER 30
#define TRAINER_DEPTSTORE_BRANDYPARTNER 31

// Route 5

#define TRAINER_ROUTE5_CLOWN_JEEVES 32

// Route 24

#define TRAINER_NUGGETBRIDGE_LASS_JARABE 33
#define TRAINER_NUGGETBRIDGE_BIRDKEEPER_ANTIPASTO 34
#define TRAINER_NUGGETBRIDGE_YOUNGSTER_SELTZER 35
#define TRAINER_NUGGETBRIDGE_BATTLEGIRL_MASLINA 36
#define TRAINER_NUGGETBRIDGE_PICNICKER_OATMEAL 37
#define TRAINER_ROUTE24_CAMPER_SHANE 38
#define TRAINER_RIVALBATTLE2 39

// Route 25

#define TRAINER_ROUTE25_BACKPACKER_JANEY 40
#define TRAINER_ROUTE25_LASS_IPHIGENIA 41
#define TRAINER_ROUTE25_POKEKID_JAMIE 42

// Bill's Garden

#define TRAINER_BILLSGARDEN_MINT 43
#define TRAINER_BILLSGARDEN_LILLIE 44

// Cerulean Gym

#define TRAINER_CERULEANGYM_SWIMMER_JULIE_BADGE1 45
#define TRAINER_CERULEANGYM_SWIMMER_JULIE_BADGE2 46
#define TRAINER_CERULEANGYM_SWIMMER_MICK_BADGE1 47
#define TRAINER_CERULEANGYM_SWIMMER_MICK_BADGE2 48
#define TRAINER_CERULEANGYM_MISTY_BADGE1 49
#define TRAINER_CERULEANGYM_MISTY_BADGE2 50
