#define TRAINER_NONE 0

// Route 6
#define TRAINER_ROUTE6_BUGCATCHER_HORACE         2

// Iced Path
#define TRAINER_ICEDPATH_SWIMMER_FRANCINE        3
#define TRAINER_ICEDPATH_CAMPER_TROY		     4
#define TRAINER_ICEDPATH_CAMPER_ROSS		     97