#define TRAINER_NONE 0

// Route 6
#define TRAINER_ROUTE6_BUGCATCHER_HORACE         2
#define TRAINER_ROUTE6_YOUNGSTER_MARUYAMA        3
#define TRAINER_ROUTE6_SUPERNERD_DIETER_1        4
#define TRAINER_ROUTE6_YOUNGSTER_MARUYAMA_2      11

// Iced Path
#define TRAINER_ICEDPATH_SWIMMER_FRANCINE        5
#define TRAINER_ICEDPATH_CAMPER_TROY		     6
#define TRAINER_ICEDPATH_CAMPER_ROSS		     7
#define TRAINER_ICEDPATH_SWIMMER_FRANCINE_2      8
#define TRAINER_ICEDPATH_SWIMMER_FRANCINE_3      9
#define TRAINER_ICEDPATH_CAMPER_ROSS_2		     10

// Route 7
#define TRAINER_ROUTE7_INFIELDER_DELBERT		 12

//Rival Battle 1
#define TRAINER_RIVALBATTLE1_PLAYER_CHOSE_RELICANTH 13
#define TRAINER_RIVALBATTLE1_PLAYER_CHOSE_SIGILYPH 14
#define TRAINER_RIVALBATTLE1_PLAYER_CHOSE_PASSIMIAN 15