#pragma once

// Special Trainer Ids.
#define TRAINER_RECORD_MIXING_FRIEND        300
#define TRAINER_RECORD_MIXING_APPRENTICE    400
#define TRAINER_EREADER                     500
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_SECRET_BASE                 1024
#define TRAINER_LINK_OPPONENT               2048
#define TRAINER_OPPONENT_C00                3072
#define TRAINER_STEVEN_PARTNER              3075
#define TRAINER_CUSTOM_PARTNER              3076

#define TRAINER_LORELEI				0x19A
#define TRAINER_LORELEI_REMATCH		0x2DF
#define TRAINER_BRUNO				0x19B
#define TRAINER_BRUNO_REMATCH		0x2E0
#define TRAINER_AGATHA				0x19C
#define TRAINER_AGATHA_REMATCH		0x2E1
#define TRAINER_LANCE				0x19D
#define TRAINER_LANCE_REMATCH		0x2E2

//Front Sprites
#define TRAINER_PIC_BRANDY 0
#define TRAINER_PIC_SHERRY 1
#define TRAINER_PIC_POHL 2
#define TRAINER_PIC_AMBASSADOR 3
#define TRAINER_PIC_VIKING 4
#define TRAINER_PIC_BOOKWORM 5
#define TRAINER_PIC_TUBER_A 6
#define TRAINER_PIC_TUBER_B 7
#define TRAINER_PIC_JANITOR 8
#define TRAINER_PIC_COOLTRAINER 9
#define TRAINER_PIC_HEX_MANIAC 0xA
#define TRAINER_PIC_JUNIOR_HEXER 0xB
#define TRAINER_PIC_BACKPACKER 0xC
#define TRAINER_PIC_CLOWN 0xD
#define TRAINER_PIC_HOOPSTER 0xE
#define TRAINER_PIC_INFIELDER 0xF
#define TRAINER_PIC_PITCHER_AND_SLUGGER 0x10
#define TRAINER_PIC_GUITARIST_A 0x11
#define TRAINER_PIC_KINDLER 0x12
#define TRAINER_PIC_BUG_MANIAC_A 0x13
#define TRAINER_PIC_BUG_MANIAC_B 0x14
#define TRAINER_PIC_KRIS 0x15
#define TRAINER_PIC_WARRIOR_GAL 0x16
#define TRAINER_PIC_FUN_OLD_MAN_A 0x17
#define TRAINER_PIC_FUN_OLD_MAN_B 0x18
#define TRAINER_PIC_ENCHANTED_BOY 0x19
#define TRAINER_PIC_VIOLA 0x1A
#define TRAINER_PIC_BUGSY 0x1B
#define TRAINER_PIC_BUGSY_POLITE 0x1C
#define TRAINER_PIC_SCHOOLKID_A 0x1D
#define TRAINER_PIC_SCHOOLKID_B 0x1E
#define TRAINER_PIC_TEAMMATES 0x1F
#define TRAINER_PIC_RAIL_STAFF 0x20
#define TRAINER_PIC_POKEFAN 0x21
#define TRAINER_PIC_EXPERT 0x22
#define TRAINER_PIC_OLDSTER 0x23
#define TRAINER_PIC_YOUNGSTER_A 0x24
#define TRAINER_PIC_CYNTHIA 0x25
#define TRAINER_PIC_NURSE 0x26
#define TRAINER_PIC_CYCLIST  0x27
#define TRAINER_PIC_IRIDA  0x28
#define TRAINER_PIC_LUCY  0x29
#define TRAINER_PIC_TRIATHLETE  0x2A
#define TRAINER_PIC_HILBERT 0x2B
#define TRAINER_PIC_HILDA 0x2C
#define TRAINER_PIC_IRIS 0x2D
#define TRAINER_PIC_BIRDKEEPER 0x2E
#define TRAINER_PIC_KUNOICHI 0x2F
#define TRAINER_PIC_HATSUMI 0x30
#define TRAINER_PIC_PARASOL_LADY 0x31
#define TRAINER_PIC_AUNT_PEPPY 0x32
#define TRAINER_PIC_RS_SOLANA 0x33
#define TRAINER_PIC_RS_ZINNIA 0x34
#define TRAINER_PIC_RS_SEB 0x35
#define TRAINER_PIC_GARCHOMP_GAVIN 0x36
#define TRAINER_PIC_MINT 0x37
#define TRAINER_PIC_HAPU 0x38
#define TRAINER_PIC_LISA 0x39
#define TRAINER_PIC_DAWN 0x3A
#define TRAINER_PIC_ELAINE 0x3B
#define TRAINER_PIC_BEA 0x3C
#define TRAINER_PIC_ALLOY 0x3D
#define TRAINER_PIC_ALLOYFINAL 0x3E
#define TRAINER_PIC_SILVER 0x3F
#define TRAINER_PIC_MALVA 0x40
#define TRAINER_PIC_POKEKID_A 0x41
#define TRAINER_PIC_POKEKID_B 0x42
#define TRAINER_PIC_BAKER 0x43
#define TRAINER_PIC_IMPOSTOR_OAK 0x44
#define TRAINER_PIC_JESSIE_JAMES 0x45
#define TRAINER_PIC_PETREL 0x46
#define TRAINER_PIC_MATORI 0x47
#define TRAINER_PIC_MARS 0x48
#define TRAINER_PIC_VENUS 0x49
#define TRAINER_PIC_COURTNEY 0x4A
#define TRAINER_PIC_SAMURAI 0x4B
#define TRAINER_PIC_FLANNERY 0x4C
#define TRAINER_PIC_WHITNEY 0x4D
#define TRAINER_PIC_SKYLA 0x4E
#define TRAINER_PIC_MAYLENE 0x4F
#define TRAINER_PIC_LILLIE 0x50
#define TRAINER_PIC_DRAKE 0x51

#define TRAINER_PIC_YOUNGSTER_B 0x52
#define TRAINER_PIC_BUG_CATCHER 0x53
#define TRAINER_PIC_LASS 0x54
#define TRAINER_PIC_SAILOR 0x55
#define TRAINER_PIC_CAMPER 0x56
#define TRAINER_PIC_PICNICKER 0x57
#define TRAINER_PIC_POKEMANIAC 0x58
#define TRAINER_PIC_SUPER_NERD 0x59
#define TRAINER_PIC_HIKER 0x5A
#define TRAINER_PIC_HECTOR_ROB 0x5B
#define TRAINER_PIC_BURGLAR 0x5C
#define TRAINER_PIC_FISHER_A 0x5D
#define TRAINER_PIC_FISHER_B 0x5E
#define TRAINER_PIC_SWIMMER_A 0x5F
#define TRAINER_PIC_FIRE_BREATHER 0x60
#define TRAINER_PIC_GAMER 0x61
#define TRAINER_PIC_GUITARIST_B 0x62
#define TRAINER_PIC_SWIMMER_B 0x63
#define TRAINER_PIC_PSYCHIC_A 0x64
#define TRAINER_PIC_KRICKETINA_KYLIE 0x65
#define TRAINER_PIC_DRAGON_TAMER 0x66
#define TRAINER_PIC_CHERISH_BALLER 0x67
#define TRAINER_PIC_BLACK_BELT_A 0x68
#define TRAINER_PIC_BLACK_BELT_B 0x69
#define TRAINER_PIC_CHASER 0x6A
#define TRAINER_PIC_MAD_SCIENTIST 0x6B
#define TRAINER_PIC_GIOVANNI 0x6C
#define TRAINER_PIC_ROCKET_GRUNT_A 0x6D
#define TRAINER_PIC_ACE_TRAINER_A 0x6E
#define TRAINER_PIC_ACE_TRAINER_B 0x6F
#define TRAINER_PIC_LORELEI 0x70
#define TRAINER_PIC_BRUNO 0x71
#define TRAINER_PIC_WILL 0x72
#define TRAINER_PIC_KAREN 0x73
#define TRAINER_PIC_BROCK 0x74
#define TRAINER_PIC_MISTY 0x75
#define TRAINER_PIC_VISQUEZ 0x76
#define TRAINER_PIC_ERIKA 0x77
#define TRAINER_PIC_JOY 0x78
#define TRAINER_PIC_BRYONY 0x79
#define TRAINER_PIC_SABRINA 0x7A
#define TRAINER_PIC_JOEY 0x7B
#define TRAINER_PIC_LANCE 0x7C
#define TRAINER_PIC_ZAKBAGON 0x7D
#define TRAINER_PIC_CHANNELER 0x7E
#define TRAINER_PIC_TWINS 0x7F
#define TRAINER_PIC_EMILY_CHARLOTTE 0x80
#define TRAINER_PIC_YOUNG_COUPLE 0x81
#define TRAINER_PIC_MIGHTY_LOVERS 0x82
#define TRAINER_PIC_SNOW_MIKU 0x83
#define TRAINER_PIC_PROF_OAK 0x84
#define TRAINER_PIC_BRENDAN_ORAS 0x85
#define TRAINER_PIC_MAY_ORAS 0x86
#define TRAINER_PIC_MAY 0x87
#define TRAINER_PIC_LEAF 0x88
#define TRAINER_PIC_ROCKET_GRUNT_B 0x89
#define TRAINER_PIC_PSYCHIC_B 0x8A
#define TRAINER_PIC_BATTLE_GIRL 0x8B
#define TRAINER_PIC_PKMN_BREEDER_A 0x8C
#define TRAINER_PIC_PKMN_BREEDER_B 0x8D
#define TRAINER_PIC_PKMN_RANGER_A 0x8E
#define TRAINER_PIC_PKMN_RANGER_B 0x8F
#define TRAINER_PIC_IDOL 0x90
#define TRAINER_PIC_RUIN_MANIAC 0x91
#define TRAINER_PIC_LADY_A 0x92
#define TRAINER_PIC_BAD_EGG 0x93
#define TRAINER_PIC_ANABEL 0x94
#define TRAINER_PIC_BLAINE 0x95
#define TRAINER_PIC_ELESA 0x96
#define TRAINER_PIC_GARDENIA 0x97
#define TRAINER_PIC_ARTIST 0x98
#define TRAINER_PIC_MARLEY 0x99
#define TRAINER_PIC_MINA 0x9A
#define TRAINER_PIC_ROSA 0x9B
#define TRAINER_PIC_SERENA 0x9C
#define TRAINER_PIC_LADY_B 0x9D
#define TRAINER_PIC_BABYSITTER 0x9E
#define TRAINER_PIC_NO1_TRAINER_A 0x9F
#define TRAINER_PIC_NO1_TRAINER_B 0xA0
#define TRAINER_PIC_ANNIEOAKLEY 0xA1
#define TRAINER_PIC_ARPIL 0xA2
#define TRAINER_PIC_MALLOW 0xA3
#define TRAINER_PIC_CLEMONT 0xA4
#define TRAINER_PIC_PSYCHIC_C 0xA5
#define TRAINER_PIC_SWIMMER_C 0xA6

//Backsprites
#define TRAINER_BACK_PIC_RED              	0
#define TRAINER_BACK_PIC_LEAF             	1
#define TRAINER_BACK_PIC_BRENDAN          	2
#define TRAINER_BACK_PIC_MAY              	3
#define TRAINER_BACK_PIC_POKE_DUDE        	4
#define TRAINER_BACK_PIC_OLD_MAN 			5

#ifndef UNBOUND //CHANGE THESE

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#else //For Unbound

#define TRAINER_ENCOUNTER_MALE         			0
#define TRAINER_ENCOUNTER_FEMALE       			1
#define TRAINER_ENCOUNTER_LADY        	 		2
#define TRAINER_ENCOUNTER_SUSPICIOUS  			3
#define TRAINER_ENCOUNTER_INTENSE      			4
#define TRAINER_ENCOUNTER_ACE_TRAINER       	5
#define TRAINER_ENCOUNTER_HIKER         		6
#define TRAINER_ENCOUNTER_MYSTERIOUS_TRAINER    7
#define TRAINER_ENCOUNTER_SAILOR      			8
#define TRAINER_ENCOUNTER_GAMBLER        		9
#define TRAINER_ENCOUNTER_ARTIST  				10
#define TRAINER_ENCOUNTER_SHADOW       			11
#define TRAINER_ENCOUNTER_LOR 					12
#define TRAINER_ENCOUNTER_ELITE_4        		13
#define TRAINER_ENCOUNTER_CYNTHIA				14

#define TRAINER_PIC_INTERVIEWER 0x3
#define TRAINER_PIC_CAMERA_MAN 0x4
#define TRAINER_PIC_POKE_KID 0x6
#define TRAINER_PIC_TUBER_M 0x7
#define TRAINER_PIC_RIVAL 0x8
#define TRAINER_PIC_RICH_GIRL 0xB
#define TRAINER_PIC_FIRE_BREATHER 0xE
#define TRAINER_PIC_BIRD_KEEPER_F 0xF
#define TRAINER_PIC_CAMPING_DUO 0x10
#define TRAINER_PIC_BIG_MO 0x13
#define TRAINER_PIC_RANCHER_M 0x15
#define TRAINER_PIC_RANCHER_F 0x16
#define TRAINER_PIC_MEL 0x18
#define TRAINER_PIC_MAXIMA 0x19
#define TRAINER_PIC_OFFICER 0x24
#define TRAINER_PIC_AKLOVE 0x26
#define TRAINER_PIC_CYCLIST_M 0x27
#define TRAINER_PIC_CYCLIST_F 0x28
#define TRAINER_PIC_JOGGER 0x29
#define TRAINER_PIC_JAX 0x2E
#define TRAINER_PIC_SCIENTIST_F 0x35
#define TRAINER_PIC_PKMN_BREEDER_M 0x3A
#define TRAINER_PIC_IDOL 0x3B
#define TRAINER_PIC_WAITER 0x3C
#define TRAINER_PIC_WAITRESS 0x3D
#define TRAINER_PIC_CYNTHIA 0x3E
#define TRAINER_PIC_SKIIER_F 0x3F
#define TRAINER_PIC_SKIIER_M 0x40
#define TRAINER_PIC_SKELI 0x41
#define TRAINER_PIC_GOLCHE 0x42
#define TRAINER_PIC_NURSE 0x43
#define TRAINER_PIC_LIXDEL 0x44
#define TRAINER_PIC_PABLO 0x47
#define TRAINER_PIC_PAULA 0x48
#define TRAINER_PIC_MARLON 0x49
#define TRAINER_PIC_IVORY 0x4A
#define TRAINER_PIC_LOR_GRUNT 0x4B
#define TRAINER_PIC_PAT 0x4C
#define TRAINER_PIC_RED 0x4D
#define TRAINER_PIC_ALICE 0x4E
#define TRAINER_PIC_CANDICE 0x4F
#define TRAINER_PIC_GAIL 0x50
#define TRAINER_PIC_PALMER 0x51
#define TRAINER_PIC_ROUGHNECK 0x60
#define TRAINER_PIC_BIRD_KEEPER_M 0x68
#define TRAINER_PIC_SHADOW_GRUNT_M 0x6D
#define TRAINER_PIC_ACE_TRAINER_M 0x6E
#define TRAINER_PIC_ACE_TRAINER_F 0x6F
#define TRAINER_PIC_MIRSKLE 0x73
#define TRAINER_PIC_ZEPH 0x74
#define TRAINER_PIC_GALAVAN 0x76
#define TRAINER_PIC_TESSY 0x77
#define TRAINER_PIC_VEGA 0x78
#define TRAINER_PIC_BENJAMIN 0x79
#define TRAINER_PIC_MEDIUM 0x7E
#define TRAINER_PIC_ACE_DUO 0x80
#define TRAINER_PIC_SHADOW_GRUNT_F 0x89

#define TRAINER_BACK_PIC_MARLON         6
#define TRAINER_BACK_PIC_POKE_KID       7
#define TRAINER_BACK_PIC_RIVAL          8
#define TRAINER_BACK_PIC_JAX            9
#define TRAINER_BACK_PIC_RED_NEW        10
#define TRAINER_BACK_PIC_CATHERINE      11
#define TRAINER_BACK_PIC_GINGER         12
#define TRAINER_BACK_PIC_ABIMBOLA       13
#define TRAINER_BACK_PIC_MAHINA         14
#define TRAINER_BACK_PIC_ALFORD         15
#define TRAINER_BACK_PIC_TESSY          16

#endif

#define F_TRAINER_FEMALE (1 << 7)

// All trainer parties specify the IV, level, and species for each Pokémon in the
// party. Some trainer parties also specify held items and custom moves for each
// Pokémon.
#define F_TRAINER_PARTY_CUSTOM_MOVESET (1 << 0)
#define F_TRAINER_PARTY_HELD_ITEM      (1 << 1)
